# Generated by Django 2.2 on 2020-12-28 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm_app', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
