# Generated by Django 2.2 on 2021-01-04 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ninja',
            old_name='fist_name',
            new_name='first_name',
        ),
    ]
